language: ruby

rvm:
  - 2.2.0

go:
  - 1.3

before_install:
  - git submodule update --init --recursive
  - ./scripts/travis/install_spiff
  - export PATH=$PATH:$PWD
script:
  - bundle exec rspec spec
  - rm spiff
  - travis_retry bundle exec bosh --parallel 10 -n sync blobs
  - ./scripts/unused_blobs
