meta:
  releases: ~
  environment: ~
  networks: ~

  openstack: (( merge ))

  bosh-network:
    cidr: (( merge ))

  stemcell:
    name: bosh-openstack-kvm-ubuntu
    version: latest

networks: 
  - name: floating
    type: vip
    cloud_properties: {}
  - name: cf1
    type: manual
    subnets:
      - name: private
        range: 172.16.1.0/24
        gateway: 172.16.1.1
        reserved: 
          - 172.16.1.5 - 172.16.1.10
        static: 
          - 172.16.1.11 - 172.16.1.20
        cloud_properties:
        net_id: (( meta.openstack.net_id ))
        security_groups: (( meta.openstack.security_groups ))
  - name: cf2
    type: manual
    subnets:
      - name: private
        range: 172.16.15.0/24
        gateway: 172.16.15.1 
        reserved:
          - 172.16.15.2 - 172.16.15.10
        static:
          - 172.16.15.11 - 172.16.15.20
        cloud_properties:
        net_id: (( meta.openstack.net_id ))
        security_groups: (( meta.openstack.security_groups )) 

properties:
  logger_endpoint:
    port: 4443

  loggregator:
    blacklisted_syslog_ranges: (( merge || [] ))

  cc: (( merge ))

  uaa:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    clients: (( merge ))

  login:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m

  dea_next:
    deny_networks:
      - 169.254.0.0/16 # Openstack Metadata endpoint
      - (( meta.bosh-network.cidr )) # BOSH network
      - (( networks.cf1.subnets.[0].range ))
      - (( networks.cf2.subnets.[0].range ))

    allow_networks:

  nats:
    address: (( jobs.nats_z1.networks.cf1.static_ips.[0] ))

  ccdb_ng:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    databases:
    - name: ccdb
      tag: cc
    db_scheme: postgres
    port: 5524
    roles:
    - name: ccadmin
      password: nil
      tag: admin
    
  ccdb: (( ccdb_ng ))

  uaadb:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    databases:
    - name: uaadb
      tag: uaa
    db_scheme: postgresql
    port: 5524
    roles:
    - name: uaaadmin
      password: nil
      tag: admin

  databases: 
    db_scheme: postgres
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: (( merge ))
      - tag: admin
        name: uaaadmin
        password: (( merge ))
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true

compilation:
  cloud_properties:
    instance_type: m1.medium

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

  - name: small_z2
    cloud_properties:
      instance_type: m1.small

  - name: medium_z1
    cloud_properties:
      instance_type: m1.medium

  - name: medium_z2
    cloud_properties:
      instance_type: m1.medium

  - name: large_z1
    cloud_properties:
      instance_type: m1.large

  - name: large_z2
    cloud_properties:
      instance_type: m1.large

  - name: runner_z1
    cloud_properties:
      instance_type: m1.large

  - name: runner_z2
    cloud_properties:
      instance_type: m1.large

  - name: router_z1
    cloud_properties:
      instance_type: m1.medium
      elbs: (( merge || ["cfrouter"] ))

  - name: router_z2
    cloud_properties:
      instance_type: m1.medium
      elbs: (( merge || ["cfrouter"] ))

# This config is for the simplest Openstack config using just one AZ.
# All values for "z2" and network "cf2" are set to null. They'll end up
# in the final 'spiff merge' manifest with zero instances.
jobs:
  - name: logs_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(0) ))

  - name: nats_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(1) ))

  - name: nfs_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(2) ))

  - name: postgres_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(3) ))

  - name: hm_z1
    instances: 0

  - name: router_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(5, 6, 15, 16, 17, 18, 19, 20) ))

  - name: loggregator_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(21, 22) ))

  - name: loggregator_trafficcontroller_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(24) ))

  - name: etcd_leader_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(9) ))

  - name: etcd_z1
    instances: 2
    networks:
      - name: cf1
        static_ips: (( static_ips(10, 11) )) 

  - name: logs_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: []

  - name: nats_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: []

  - name: router_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: []

  - name: etcd_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: []

  - name: loggregator_z2
    instances: 0
    networks:
     - name: cf2
       static_ips: []

  - name: loggregator_trafficcontroller_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: []

  - name: uaa_z2
    instances: 0

  - name: api_z2
    instances: 0

  - name: api_worker_z2
    instances: 0

  - name: hm9000_z2
    instances: 0

  - name: runner_z2
    instances: 0
